version: 2
updates:

  # Manage Github Actions versions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "ci:"
    labels:
      - c:deps
      - c:testing

  # Manage client-sdk/go package versions.
  - package-ecosystem: gomod
    directory: client-sdk/go/
    schedule:
      interval: daily
    commit-message:
      prefix: "client-sdk/go:"
    labels:
      - c:deps
      - c:client-sdk/go
    ignore:
      # oasis-core is manually kept up to date.
      - dependency-name: github.com/oasisprotocol/oasis-core/go

  # Manage tests/e2e package versions.
  - package-ecosystem: gomod
    directory: tests/e2e
    schedule:
      interval: daily
    commit-message:
      prefix: "tests/e2e:"
    labels:
      - c:deps
      - c:testing
    ignore:
      # oasis-core is manually kept up to date.
      - dependency-name: github.com/oasisprotocol/oasis-core/go
      # client-sdk is replaced with the local up-to-date version.
      - dependency-name: github.com/oasisprotocol/oasis-sdk/client-sdk/go

  # Manage Rust package versions.
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "runtime-sdk:"
    labels:
      - c:deps
      - c:runtime-sdk
    ignore:
      # oasis-core-runtime is manually kept up to date.
      - dependency-name: oasis-core-runtime

  # Manage npm package versions.
  - package-ecosystem: npm
    directory: client-sdk/ts-web
    schedule:
      interval: daily
    commit-message:
      prefix: "client/ts-web:"
    labels:
      - c:deps
      - c:client-sdk/typescript
