# Runtime Transactions

This section describes the format of all supported runtime methods and queries
with references to Go, Rust and TypeScript bindings in Oasis SDK.

<!-- DO NOT EDIT LIST OF TRANSACTIONS BELOW MANUALLY! The list was generated by
     tools/extract-runtime-txs. -->

<!-- markdownlint-disable line-length -->

<!--- OASIS_RUNTIME_TRANSACTIONS -->

<!-- markdownlint-enable line-length -->
