name: Unit Test Rust Worskapce with Coverage
description: Run unit tests on a Rust workspace with coverage and uploads results to codecov
inputs:
  manifest_path:
    description: Path to the Cargo.toml manifest of the Rust sources to build and test
    default: ${{ github.workspace }}/Cargo.toml
    required: false
runs:
  using: composite
  steps:
    - name: Install tarpaulin
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-tarpaulin@0.32.5

    - name: Unit tests with coverage
      shell: bash
      run: cargo tarpaulin --out Xml --avoid-cfg-tarpaulin --manifest-path "$MANIFEST_PATH" -- --test-threads 1
      env:
        # Required as tarpaulin doesn't honor .cargo/config.
        RUSTFLAGS: -C target-feature=+aes,+ssse3
        MANIFEST_PATH: ${{ inputs.manifest_path }}

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v5.5.1
      with:
        use_oidc: true  # Upload authentication to avoid rate-limiting

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: cobertura.xml
        overwrite: true
