# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-audit

# Trigger the workflow when:
on:
  # A push modifies one of the matches files.
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

# Cancel in-progress jobs on same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  audit:
    # NOTE: This name appears in GitHub's Checks API.
    name: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
